check to see if fully multi-arch

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -3,8 +3,11 @@ name: Release
 
 on:
   push:
-    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
-
+    branches: [ main ]
+    paths: 
+      - "pom.xml"
+  workflow_dispatch:
+    
 permissions:
   contents: read
   packages: write
@@ -23,6 +26,13 @@ jobs:
         username: ${{ github.actor }}
         password: ${{ secrets.GH_TOKEN_CAROLYN }}
 
+    - name: Setup Java  
+      uses: actions/setup-java@v4
+      with:
+        distribution: temurin
+        java-version: "17"
+        cache: maven
+
     # - name: Parse version info from lib-version
     #   run: |
     #     VERSION=${GITHUB_REF:11}
@@ -38,13 +48,21 @@ jobs:
       run: |
         echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
 
+    - name: Verfy versions match tag and pom.xml
+      if: startsWith(github.ref, 'refs/tags/')
+      run: |
+        if [ "v${VERSION}" != "${GITHUB_REF_NAME}" ]; then  
+          echo "ERROR: tag (${GITHUB_REF_NAME}) does not match version in pom.xml (v${VERSION})"
+          exit 1
+        fi
+
     - name: Extract metadata
       id: meta
       uses: docker/metadata-action@v4
       with:
         images: ghcr.io/doda2025-team3/app
         tags: |
-          type=raw, value=${{ env.VERSION }}
+          type=raw,value=${{ env.VERSION }}
 
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v3
@@ -58,6 +76,7 @@ jobs:
         platforms: linux/amd64,linux/arm64
         context: .
         push: ${{ github.event_name != 'pull_request' }}
+        provenance: false
         tags: ${{ steps.meta.outputs.tags }}
         labels: ${{ steps.meta.outputs.labels }}
 
